# Speed up script by not using unicode
export LC_ALL=C
export LANG=C

# See this wiki page for more info:
# https://github.com/dylanaraps/neofetch/wiki/Customizing-Info
print_info () {
    info title
    info underline

    info "OS" distro
    info "Host" model
    info "Packages" packages
    info "Kernel" kernel
    info "Shell" shell
    info "Resolution" resolution
    info underline

    info "Uptime" uptime
    info "Terminal" term
    info "DE" de
    info "WM" wm
    info "WM Theme" wm_theme
    info "Theme" theme
    info "Icons" icons
    # info "Terminal Font" term_font
    info underline

    info "CPU" cpu
    info "GPU" gpu
    info "Memory" memory
    info "CPU Usage" cpu_usage
    info "Disk" disk
    info "Battery" battery
    # info "Font" font
    # info "Song" song
    info underline
    
    # info "Public IP" public_ip
    # info "Local IP" local_ip
    # info "Users" users
    # info "Birthday" birthday

    # info line_break
    # info cols
}

# Kernel
kernel_shorthand="off"

# Distro
distro_shorthand="tiny"
os_arch="on"

# Uptime
uptime_shorthand="on"

# Shell
shell_path="off"
shell_version="off"

# CPU
speed_type="bios_limit"
speed_shorthand="on"
cpu_brand="on"
cpu_speed="on"
cpu_cores="off"
cpu_temp="off"

# GPU
gpu_brand="on"
gpu_type="all"

# Resolution
refresh_rate="off"

# Gtk Theme / Icons / Font
gtk_shorthand="off"
gtk2="on"
gtk3="on"

# IP Address
public_ip_host="http://ident.me"

# Disk
disk_show=('/')
disk_subtitle="mount"

song_shorthand="off"
install_time="on"
install_time_format="12h"
colors=distro
bold="on"
underline_enabled="on"
underline_char="-"
block_range=(0 7)
color_blocks="off"
block_width=3
block_height=1
bar_char_elapsed="-"
bar_char_total="="
bar_border="on"
bar_length=15
bar_color_elapsed="distro"
bar_color_total="distro"
cpu_display="off"
memory_display="off"
battery_display="off"
disk_display="off"
image_backend="ascii"
image_source="auto"
ascii_colors=distro
ascii_bold="on"
image_loop="off"
thumbnail_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/thumbnails/neofetch"
crop_mode="normal"
crop_offset="center"
image_size="auto"
gap=3
yoffset=0
xoffset=0
background_color=
scrot="off"
scrot_cmd="auto"
scrot_name="neofetch-$(date +%F-%I-%M-%S-${RANDOM}).png"
image_host="teknik"
stdout="off"
config_version="3.3.0"