# Unbind default keys
unbind C-b
unbind-key x # unbind-key “x” from it’s current job of “ask and then close”

# Set ctrl-a as a prefix
set -g prefix C-a
bind C-a send-prefix

# Enable mouse support
set -g mouse on 

# Tmux adds a short, almost imperceptible delay between the commands that can 
# cause funny behavior when running vim inside tmux.
set-option -s escape-time 0

# Enable color support inside of tmux.
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"

set -g base-index 1 # Windows index will start with 1
setw -g pane-base-index 1 # pane index will start with 1
set-option -g renumber-windows on         

# default names are too vague to see. Let me name it.
# set-option -wg automatic-rename off

# Ensure window titles get renamed automatically.
setw -g automatic-rename

# Set vim key for copy mode
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Reload the tmux config
bind-key r source-file ~/.tmux.conf \; display "Config Reloaded!"

bind-key x kill-pane       # rebind-key it to just “close”
bind-key X kill-session    # key combo for killing the entire session

# Vim-like pane switching
# bind -r ^ last-window
# bind -r k select-pane -U
# bind -r j select-pane -D
# bind -r h select-pane -L
# bind -r l select-pane -R

# # Right Side
# set-option -g status-right-length 50   # default 50
# set-option -g status-right "#[fg=black,dim,bg=default] uptime: #(uptime | cut -f 4-5 -d\" \" | cut -f 1 -d\",\")"
