#!/usr/bin/env bash

### OPTIONS AND VARIABLES ###

dotfiles_path="$(
    cd "$(dirname "$0")"
    pwd
)"
cd "$dotfiles_path"

config_path="${XDG_CONFIG_HOME:-$HOME/.config}"

GREEN=$(tput setaf 2)
NORMAL=$(tput sgr0)

# List that should be inside ~/ directory
home_directory=(
  .asdfrc
  .bashrc
  .profile
  .xinitrc
  .xprofile
  .Xresources
  .zprofile
)

# List for ~/.config folder
config_directory=(
  alacritty
  bspwm
  calcurse
  dunst
  git
  htop
  gitui
  gtk-3.0
  # i3
  lf
  mpv
  navi
  newsboat
  nsxiv
  nvim
  pcmanfm
  picom
  pipewire
  polybar
  rofi
  shell
  sxhkd
  tig
  tmux
  transmission-daemon/settings.json
  wget
  zathura
  zsh
  mimeapps.list
  pavucontrol.ini
  screenkey.json
  # hypr
  # waybar
)

### FUNCTIONS ###

logger() {
  msg=$1

  printf "\n${GREEN}%s${NORMAL} %s \n" "[LOG]" "$msg"
}

### SCRIPT EXECUTION ###

# Output brief information before running the script
echo "///////////////////////////////////////////////////////////////////////"
echo -e "///////////////////// ${GREEN}Created by Witty Judge${NORMAL} //////////////////////////"
echo -e "//////////// https://github.com/WIttyJudge/dotfiles ///////////////"
echo "///////////////////// Dotfile Setup ////////////////////////////"
echo "///////////////////////////////////////////////////////////////////////"

logger "Home directory setup"
for i in ${home_directory[@]}; do
  ln -sfv $dotfiles_path/$i $HOME/$i
done

logger "Config directory setup"
for i in ${config_directory[@]}; do
  [ -d $config_path/$i ] && rm -rf $config_path/$i

  ln -sfv $dotfiles_path/.config/$i $config_path/$i
done

logger "Local directory setup"

logger "Applications"
ln -sfv $dotfiles_path/.local/share/applications/* $HOME/.local/share/applications/

logger "Icons"
ln -sfv $dotfiles_path/.local/share/icons/fontawesome/* $HOME/.local/share/icons/fontawesome/

logger "Bins"
ln -sfv $dotfiles_path/.local/bin/* $HOME/.local/bin/

logger "Background wallpaper"
ln -sfv $dotfiles_path/.local/share/bg $HOME/.local/share/
