#!/usr/bin/env bash

### OPTIONS AND VARIABLES ###

dotfiles_path="${DOTFILES:-$HOME/dotfiles}"
config_path="${XDG_CONFIG_HOME:-$HOME/.config}"

GREEN=$(tput setaf 2)
NORMAL=$(tput sgr0)

# List that should be inside ~/ directory
home_directory=(
  .bashrc
  .profile
  .xinitrc
  .xprofile
  .Xresources
  .zprofile
)

# List for ~/.config folder
config_directory=(
  alacritty
  bspwm
  calcurse
  dunst
  git
  # i3
  lf
  mpv
  navi
  newsboat
  nsxiv
  nvim
  pipewire
  # polybar
  # rofi
  shell
  sxhkd
  tmux
  transmission-daemon/settings.json
  wget
  zsh
  mimeapps.list
  pavucontrol.ini
)

### FUNCTIONS ###

logger() {
  msg=$1

  printf "\n${GREEN}%s${NORMAL} %s \n" "[LOG]" "$msg"
}

### SCRIPT EXECUTION ###

# Output brief information before running the script
echo "///////////////////////////////////////////////////////////////////////"
echo -e "///////////////////// ${GREEN}Created by Witty Judge${NORMAL} //////////////////////////"
echo -e "//////////// https://github.com/WIttyJudge/dotfiles ///////////////"
echo "///////////////////// Dotfile Setup /////////////////////////"
echo "///////////////////////////////////////////////////////////////////////"
read -n 1 -r -s -p $'//////////////////// Press any key to continue ////////////////////////\n\n'

logger "Home directory setup"
for i in ${home_directory[@]}; do
  ln -sfv $dotfiles_path/$i $HOME/$i
done

logger "Config directory setup"
for i in ${config_directory[@]}; do
  [ -d $config_path/$i ] && rm -rf $config_path/$i

  ln -sfv $dotfiles_path/.config/$i $config_path/$i
done

# logger "Scripts setup"
# stow --adopt -v -R -t ~ scripts

logger "Local directory setup"
logger "Applications folder"
[ ! -d $HOME/.local ] && mkdir -p $HOME/.local/share
[ ! -d $HOME/.local/share/applications ] && mkdir -p $HOME/.local/share/applications
# [ -d $HOME/.local/share/applications ] && rm -rf $HOME/.local/share/applications
ln -sfv $dotfiles_path/.local/share/applications/* $HOME/.local/share/applications/

logger "Bin folder"
[ ! -d $HOME/.local/bin ] && mkdir -p $HOME/.local/bin
ln -sfv $dotfiles_path/.local/bin/* $HOME/.local/bin/
