#!/bin/sh

# To execute this file you need to press ctrl + x and then press key you can see below.
while read file
do
  case "$1" in
	"w")
		cp "$file" ~/Pictures/wallpapers/wp.png &&
		xwallpaper --zoom ~/Pictures/wallpapers/wp.png &&
		notify-send "$file moved to wallpapers" ;;
	"r")
		convert -rotate 90 "$file" "$file" ;;
	"R")
		convert -rotate -90 "$file" "$file" ;;
	"y")
		echo -n "$file" | xclip -selection clipboard &&
		notify-send "$file copied to clipboard" ;;
	"Y")
		readlink -f "$file" | xclip -selection clipboard &&
		notify-send "$(readlink -f "$file") copied to clipboard" ;;
	"d")
		[ "$(printf "Yes\\nNo" | dmenu -i -p "Delete $file?")" == "Yes" ] && rm "$file" && notify-send "$file deleted" ;;
	"i")
		notify-send "File information" "$(mediainfo $file)" ;;
  esac
done
