#!/usr/bin/env sh

# sudo not required for some system commands
for x in systemctl sv pacman downgrade; do
  alias $x="sudo $x"
done

# useful
alias \
  s="sudo " \
  p="sudo pacman " \
  ping="ping -c 3 youtube.com" \
  e="$EDITOR" \
  update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg" \
  send-file="qrcp " \
  receive-file="qrcp receive" \
  open="xdg-open " \
  sxiv="nsxiv " \
  lg="lazygit " \
  lf="lfrun " \

# for testing
alias \
  t-micro="arecord -vv -f dat /dev/null" \
  t-sound="speaker-test -c2 -t wav" \
  t-webcam="mpv av://v4l2:/dev/video0 --profile=low-latency --untimed" \

# fast cd
alias \
  ..="cd .." \

# commands
alias dotfiles="cd ~/dotfiles && $EDITOR"

# rewrite standard commands
alias \
  cat="bat" \
	cp="cp -iv" \
	mv="mv -iv" \
	mkdir="mkdir -v" \
  wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"

alias ls="exa -la --group-directories-first --icons" # doesn't show hidden files
alias ls.="exa -dl .* --icons" # shows only hidden files
alias lst="exa -l --sort newest --icons" # sort output by newest file
alias la="exa -la --group-directories-first --icons"  # all files and dirs

# git
alias \
  g="git " \
  gs="git status" \
  ga="git add" \
  gc="git commit" \
  gp="git push" \
  glog="git log --graph --oneline --decorate" \

# docker
alias \
  d="docker " \
  dc="docker-compose " \
