#!/usr/bin/env sh

# sudo not required for some system commands
for x in mount umount sv pacman su shutdown poweroff reboot downgrade ; do
  alias $x="sudo $x"
done; unset x

command -v curlie    &> /dev/null    && alias curl='curlie'
# command -v trash-put &> /dev/null    && alias rm='trash-put'
command -v bat       &> /dev/null    && alias c='bat'         || alias c='cat'

# useful
alias \
  s="sudo " \
  p="sudo pacman " \
  e="$EDITOR" \
  se="sudoedit " \
  lg="lazygit " \
  man="fman" \
  open="xdg-open " \
  whoami="whoami && curl -s ident.me" \

# for testing
alias \
  t-micro="arecord -vv -f dat /dev/null" \
  t-sound="speaker-test -c2 -t wav" \
  t-webcam="mpv av://v4l2:/dev/video0 --profile=low-latency --untimed" \

# fast cd
alias \
  ..="cd .." \

# commands
alias dotfiles="cd ~/dotfiles && $EDITOR"

# rewrite standard commands
alias \
	cp="cp -iv" \
	mv="mv -iv" \
  bc="bc -ql" \
	mkdir="mkdir -pv" \
  wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"

alias ls="exa -la --group-directories-first --icons=auto" # doesn't show hidden files
alias ls.="exa -dl .* --icons=auto" # shows only hidden files
alias lst="exa -l --sort newest --icons=auto" # sort output by newest file
alias la="exa -la --group-directories-first --icons=auto"  # all files and dirs

# git
alias \
  g="git " \
  gs="git status" \
  ga="git add" \
  gc="git commit" \
  gp="git push" \
  glog="git log --graph --oneline --decorate" \

# docker
alias \
  d="docker " \
  dc="docker-compose " \

if command -v pacman >/dev/null 2>&1 && command -v yay >/dev/null 2>&1 && command -v fzf >/dev/null 2>&1; then
  alias fyay="yay -Slq --aur | fzf --multi --preview 'yay -Sii {1}' --preview-window=down:75% | xargs -ro yay -S --aur"
  alias fpac="pacman -Slq | fzf --multi --preview 'pacman -Si {1}' --preview-window=down:75% | xargs -ro sudo pacman -S"
fi
