#!/usr/bin/env zsh

#  +----------------------------------------------------------+
#  |                           Git                            |
#  +----------------------------------------------------------+

function acp() {
  git commit -am "Auto commit"
  git push origin master
}

#  +----------------------------------------------------------+
#  |                           Tmux                           |
#  +----------------------------------------------------------+

function tkill() {
  tmux ls -F '#{session_name}' |\
    fzf --header='Kill session' |\
    xargs -I {} tmux kill-session -t {}
}

# +----------------------------------------------------------+
# |                          Docker                          |
# +----------------------------------------------------------+

# Select a docker image or images to remove
function drmi() {
  docker images | sed 1d | fzf -q "$1" --no-sort -m --tac | awk '{ print $3 }' | xargs -r docker rmi
}

#  +----------------------------------------------------------+
#  |                 Simple useful functions                  |
#  +----------------------------------------------------------+
# https://github.com/junegunn/fzf/wiki/Examples#man-pages

# Search man pages.
function fman() {
	MAN="/usr/bin/man"

	if [ -n "$1" ]; then
		$MAN "$@"
		return $?
	else
		$MAN -k . | awk '{print $1}' | fzf | xargs -r $MAN
		return $?
	fi
}

# fkill - kill processes - list only the ones you can kill. Modified the earlier script.
# https://github.com/junegunn/fzf/wiki/Examples#processes
function fkill() {
	local pid 
	if [ "$UID" != "0" ]; then
		pid=$(ps -f -u $UID | sed 1d | fzf -m | awk '{print $2}')
	else
		pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')
	fi  

	if [ "x$pid" != "x" ]
	then
		echo $pid | xargs kill -${1:-9}
	fi  
}

# example: repeat 3 ping google.com
function repeat() {
  local i max
  max=$1; shift;
  for ((i=1; i <= max ; i++)); do
    eval "$@";
  done
}

# Converts files to backup.
function bak() {
	for source in "$@"; do
		mv "$source" "$source.bak"
	done
}

# Converts backup files back.
function unbak() {
	for source in "$@"; do
		result=${source/.bak/}

		mv "$source" "$result"
	done
}

# Search env variables
function vars() {
	env | fzf | cut -d= -f2
}

# Prevent 'zsh: command not found: $'
function $ () {
  "$@"
}

function nvims() {
  items=("default" "kickstart")
  config=$(printf "%s\n" "${items[@]}" | fzf --prompt=" Neovim Config  " --height=~50% --layout=reverse --border --exit-0)
  if [[ -z $config ]]; then
    echo "Nothing selected"
    return 0
  elif [[ $config == "default" ]]; then
    config=""
  fi
  NVIM_APPNAME=$config nvim $@
}

function whatsmyip() {
	# Internal IP Lookup.
	echo -n "Internal IP: "
	if command -v ip >/dev/null 2>&1; then
		ip -o -4 route get 1.1.1.1 2>/dev/null | awk '{for (i=1; i<=NF; i++) if ($i == "src") {print $(i+1); exit}}'
	elif command -v ifconfig >/dev/null 2>&1; then
		ifconfig | awk '/inet / && $2 != "127.0.0.1" {print $2; exit}'
	else
		echo "unknown"
	fi

	# External IP Lookup
	echo -n "External IP: "
	if command -v curl >/dev/null 2>&1; then
		curl -4fsS --max-time 5 https://ifconfig.me || printf '%s' "unknown"
		echo
	else
		echo "curl not installed"
	fi
}
