#!/usr/bin/env sh

# sudo not required for some system commands
for x in mount umount sv pacman su shutdown poweroff reboot downgrade ; do
  alias $x="sudo $x"
done; unset x

command -v curlie    &> /dev/null    && alias curl='curlie'
# command -v trash-put &> /dev/null    && alias rm='trash-put'
command -v bat       &> /dev/null    && alias c='bat'         || alias c='cat'

# useful
alias \
  s="sudo " \
  p="sudo pacman " \
  e="$EDITOR" \
  se="sudoedit " \
  lg="lazygit " \
  man="fman" \
  whoami="whoami && curl -s ident.me" \

# fast cd
alias \
  ..="cd .." \

# rewrite standard commands
alias \
	cp="cp -iv" \
	mv="mv -iv" \
  bc="bc -ql" \
	mkdir="mkdir -pv"

alias ls="exa -la --group-directories-first --icons=auto" # doesn't show hidden files
alias ls.="exa -dl .* --icons=auto" # shows only hidden files
alias lst="exa -l --sort newest --icons=auto" # sort output by newest file
alias la="exa -la --group-directories-first --icons=auto"  # all files and dirs

# docker
alias \
  d="docker " \
  dc="docker-compose " \

if command -v pacman >/dev/null 2>&1 && command -v yay >/dev/null 2>&1 && command -v fzf >/dev/null 2>&1; then
  alias fyay="yay -Slq --aur | fzf --multi --preview 'yay -Sii {1}' --preview-window=down:75% | xargs -ro yay -S --aur"
  alias fpac="pacman -Slq | fzf --multi --preview 'pacman -Si {1}' --preview-window=down:75% | xargs -ro sudo pacman -S"
fi
