# This file is sources inside ~/.config/tmux/.tmux.conf

## COLORSCHEME: catppuccin mocha
set-option -g status "on"

# default statusbar color
set-option -g status-style bg=#1e1e2e,fg=#cdd6f4 # bg=base, fg=text

# default window title colors
set-window-option -g window-status-style bg=#f9e2af,fg=#1e1e2e # bg=yellow, fg=base

# default window with an activity alert
set-window-option -g window-status-activity-style bg=#1e1e2e,fg=#bac2de # bg=base, fg=subtext1

# active window title colors
set-window-option -g window-status-current-style bg=#f38ba8,fg=#1e1e2e # bg=red, fg=base

# pane border
set-option -g pane-active-border-style fg=#a6adc8 # subtext0
set-option -g pane-border-style fg=#313244 # surface0

# message infos
set-option -g message-style bg=#45475a,fg=#cdd6f4 # bg=surface1, fg=text

# writing commands inactive
set-option -g message-command-style bg=#45475a,fg=#cdd6f4 # bg=surface1, fg=text

# pane number display
set-option -g display-panes-active-colour #a6adc8 # subtext0
set-option -g display-panes-colour #1e1e2e # base

# clock
set-window-option -g clock-mode-colour #89b4fa #blue

# bell
set-window-option -g window-status-bell-style bg=#f38ba8,fg=#11111b # bg=red, fg=crust

## Theme settings mixed with colors (unfortunately, but there is no cleaner way)
set-option -g status-justify "left"
set-option -g status-left-style none
set-option -g status-left-length "80"
set-option -g status-right-style none
set-option -g status-right-length "80"
set-window-option -g window-status-separator ""

set-option -g status-left "#[bg=#585b70,fg=#bac2de] #S #[bg=#1e1e2e,fg=#585b70,nobold,noitalics,nounderscore]"
set-option -g status-right "#[bg=#1e1e2e,fg=#45475a nobold, nounderscore, noitalics]#[bg=#45475a,fg=#9399b2] %Y-%m-%d  %H:%M #[bg=#45475a,fg=#bac2de,nobold,noitalics,nounderscore]#[bg=#bac2de,fg=#1e1e2e] #h "

set-window-option -g window-status-current-format "#[bg=#f9e2af,fg=#1e1e2e,nobold,noitalics,nounderscore]#[bg=#f9e2af,fg=#45475a] #I #[bg=#f9e2af,fg=#45475a,bold] #W#{?window_zoomed_flag,*Z,} #[bg=#1e1e2e,fg=#f9e2af,nobold,noitalics,nounderscore]"
set-window-option -g window-status-format "#[bg=#45475a,fg=#1e1e2e,noitalics]#[bg=#45475a,fg=#cdd6f4] #I #[bg=#45475a,fg=#cdd6f4] #W #[bg=#1e1e2e,fg=#45475a,noitalics]"
