config-version = 2

after-startup-command = [
  'exec-and-forget borders'
]

start-at-login = true

auto-reload-config = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
# Hides the JankyBorders border when only one window is on the focused.
on-focus-changed = [
    'exec-and-forget [ $(aerospace list-windows --workspace focused | wc -l) -eq 1 ] && borders width=0.0 || borders width=2.0',
]

[focus-follows-mouse]
enabled = true

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 5
inner.vertical =   5
outer.left =   10
outer.bottom = 10
outer.top =    10
outer.right =  10

# +----------------------------------------------------------+
# |                          Binds                           |
# +----------------------------------------------------------+

[mode.main.binding]
    # Open terminal
    # alt-enter = 'exec-and-forget open -na Ghostty'
    alt-enter = 'exec-and-forget osascript -e "tell application \"Ghostty\" to new window"'


    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    # alt-q = 'close'
    alt-q = 'close --quit-if-last-window'

    alt-f = 'fullscreen'
    alt-o = 'layout floating tiling'
    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # Move focus
    alt-h = 'focus --wrap-around left'
    alt-j = 'focus --wrap-around down'
    alt-k = 'focus --wrap-around up'
    alt-l = 'focus --wrap-around right'

    # Swap the active window with another window
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # Resizing the active window
    alt-shift-right = 'resize width -50'
    alt-shift-left = 'resize width +50'
    alt-shift-down = 'resize height -50'
    alt-shift-up = 'resize height +50'

    # Switch workspaces with mainMod + [0-9]
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 0'

    # Swap the active window with another window
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    alt-shift-0 = 'move-node-to-workspace 0'

# +----------------------------------------------------------+
# |                       Window Rules                       |
# +----------------------------------------------------------+

[[on-window-detected]]
if = 'test %{app-bundle-id} = com.google.Chrome'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if = 'test %{app-bundle-id} = com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if = 'test %{app-bundle-id} = ru.keepcoder.Telegram'
run = ['move-node-to-workspace 5', 'layout floating']

[[on-window-detected]]
if = 'test %{app-bundle-id} = com.hnc.Discord'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if = 'test %{app-bundle-id} = org.pqrs.Karabiner-Elements.Settings'
run = 'layout floating'
