#! /bin/sh

################
#  Autostarts  #
################

launchpolybar &
setbg &

killall bspswallow
pidof bspswallow | bspswallow &

#########################
#  BSPWM configuration  #
#########################

workspaces() {
	name=1
	for monitor in $(bspc query -M); do
		bspc monitor "${monitor}" -n "$name" -d 1 2 3 4 5 6 7
		(( name++ ))
	done
}

workspaces

bspc config top_padding           32
bspc config bottom_padding         0
bspc config left_padding           0
bspc config right_padding          0
bspc config border_width           2
bspc config window_gap            10

# border colors basic
# bspc config focused_border_color '#302D41'
# bspc config normal_border_color '#1e1e28'
bspc config normal_border_color "#313244"
bspc config focused_border_color "#7f849c"

#####################
#  Global Settings  #
#####################

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config borderless_monocle						true
bspc config single_monocle								true
bspc config focus_follows_pointer         true
bspc config remove_disabled_monitors      true
bspc config remove_unplugged_monitors     true
bspc config merge_overlapping_monitors    true

###########
#  Rules  #
###########

# Delete all automatically set rules
# bspc rule -r "*"
# Set rules for all floating windows
# bspc rule -a \* rectangle 800x600+0+0 center=true

bspc rule -a Chromium desktop='^1'
bspc rule -a firefox desktop='^1'
bspc rule -a Brave desktop='^1'
bspc rule -a jetbrains-rubymine desktop='^3' follow=off
bspc rule -a jetbrains-idea-ce desktop='^3' follow=off
bspc rule -a TelegramDesktop desktop='^4' state=floating follow=on
bspc rule -a Slack desktop='^4'
bspc rule -a discord desktop='^4'
bspc rule -a zoom desktop='^4'
bspc rule -a Steam desktop='^5'
bspc rule -a Lutris desktop='^5'
bspc rule -a Battle.net desktop='^5'

bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Print state=floating
bspc rule -a System-config-printer.py state=floating rectangle=800x600+0+0 center=on
bspc rule -a Simple-scan state=floating
bspc rule -a Blueberry.py state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Pcmanfm state=floating
bspc rule -a Viewnior state=floating
