#! /bin/sh

################
#  Autostarts  #
################

launchpolybar &

killall bspswallow
pidof bspswallow | bspswallow &

#########################
#  BSPWM configuration  #
#########################
 
# bspc monitor eDP-1 -d 1 2 3 4 5 6 7
bspc monitor DP-2 -d 1 2 3 4 5 6 7

bspc config top_padding           32
bspc config bottom_padding         0
bspc config left_padding           0
bspc config right_padding          0
bspc config border_width           2
bspc config window_gap            10

# border colors basic
bspc config focused_border_color '#302D41'
bspc config normal_border_color '#1e1e28'

#####################
#  Global Settings  #
#####################

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer         true
bspc config remove_disabled_monitors      true
bspc config remove_unplugged_monitors     true
bspc config merge_overlapping_monitors    true

###########
#  Rules  #
###########

# Delete all automatically set rules
# bspc rule -r "*"
# Set rules for all floating windows
# bspc rule -a \* rectangle 800x600+0+0 center=true

bspc rule -a Chromium desktop='^1'
bspc rule -a firefox desktop='^1'
bspc rule -a Brave desktop='^1'
bspc rule -a jetbrains-rubymine desktop='^3'
bspc rule -a TelegramDesktop desktop='^4' state=floating follow=on
bspc rule -a Slack desktop='^4'
bspc rule -a discord desktop='^4'
bspc rule -a zoom desktop='^4'
bspc rule -a Steam desktop='^5'
bspc rule -a Lutris desktop='^5'
bspc rule -a Battle.net desktop='^5'

bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a Nm-connection-editor state=floating
bspc rule -a system-config-printer state=floating rectangle=800x600+0+0 center=on
bspc rule -a Simple-scan state=floating
bspc rule -a Blueberry.py state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Pcmanfm state=floating
