[general]
import = ["/home/wittyjudge/.config/alacritty/themes/catppuccin-mocha.toml"]

[bell]
animation = "EaseOutExpo"

[cursor]
style = "Underline"
vi_mode_style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "JetBrainsMono NFM"
style = "Medium"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
chars = "gc"
key = "Slash"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "C"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "Last"
key = "Key4"
mode = "Vi"

[[mouse.bindings]]
action = "Copy"
mouse = "Middle"

[scrolling]
multiplier = 1

[window]
opacity = 0.9

[window.padding]
x = 1
y = 1
