[general]
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[bell]
animation = "EaseOutExpo"

[cursor]
style = "Underline"
vi_mode_style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"

[scrolling]
multiplier = 1

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.8
option_as_alt = "Both"

[window.padding]
x = 0
y = 0
