;    ___      _       _
;   / _ \___ | |_   _| |__   __ _ _ __
;  / /_)/ _ \| | | | | '_ \ / _` | '__|
; / ___/ (_) | | |_| | |_) | (_| | |
; \/    \___/|_|\__, |_.__/ \__,_|_|
;               |___/

include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/modules.ini

[settings]
format-foreground =
format-underline = ${colors.primary}
format-background = ${colors.background-alt}
format-padding = 1
format-margin = 0
format-offset = 0
screenchange-reload = true

;https://github.com/jaagr/polybar/wiki/Configuration#global-wm-settings
[global/wm]
margin-top = 0
margin-bottom = 0

[bar/main]
monitor = ${env:MONITOR:}
wm-restack = bspwm
fixed-center = false
enable-ipc = true

modules-left = bspwm xwindow 
modules-right = microphone memory cpu disk temp pacman-packages weather brightness volume battery internet date

font-0 = JetBrainsMonoMedium:pixelsize=10
; font-0 = HackNerdFont:pixelsize=10;5
; font-1 = NotoEmoji:fontformat=truetype:scale=10:antialias=false
font-1 = JoyPixels:fontformat=truetype:scale=8:antialias=false

width = 100%
; This is around 32 pixels
height = 3%

; underline-size = 3

background = ${colors.background}
foreground = ${colors.foreground}

module-margin = 1.5

tray-position = right
tray-maxsize = 22
tray-background = ${colors.background-alt}
tray-padding = 3

cursor-click = pointer
cursor-scroll = default
