[colors]
background = ${xrdb:background}
background-wm = ${xrdb:color8}
background-alt = ${xrdb:color0}
foreground = ${xrdb:foreground}
foreground-alt = ${xrdb:color7}
primary = ${xrdb:color4}
alert = ${xrdb:color1}

[settings]
format-foreground =
format-underline = ${colors.primary}
format-background = ${colors.background-alt}
format-padding = 1
format-overline =
format-margin = 0
; format-offset =
screenchange-reload = true

;==========================================================

[global/wm]
;https://github.com/jaagr/polybar/wiki/Configuration#global-wm-settings
margin-top = 0
margin-bottom = 10

;==========================================================

[bar/top-bar]
;https://github.com/jaagr/polybar/wiki/Configuration
;monitor = ${env:MONITOR:HDMI-1}

separator = 
bottom = false
fixed-center = true
enable-ipc = true
wm-restack = bspwm
override-redirect = false

width = 100%
height = 24
offset-x = 0
offset-y = 0
radius = 0.0

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2
line-color = #f00

border-size = 0
border-color = #00000000

padding = 1

; module-margin = 1
module-margin-left = 0
module-margin-right = 1

font-0 = "monospace:pixelsize=9"
; font-0 = JetBrainsMonoMedium:pixelsize=9;
; font-1 = NotoEmoji:fontformat=truetype:scale=10:antialias=false;
font-1 = JoyPixels:fontformat=truetype:scale=8:antialias=false;

modules-left = bspwm xwindow
; modules-center = mem memory cpu filesystem pacman-updates weather
; modules-right = xkeyboard pulseaudio wireless-network eth battery date 

modules-right = microphone memory cpu disk temp pacman-packages volume battery date
; cpu-temperature weather

tray-position = right
tray-padding = 1
tray-background = ${colors.background-alt}
tray-offset-x = 0
tray-offset-y = 0
tray-scale = 1.0

cursor-click = pointer
cursor-scroll = ns-resize

;==========================================================

[module/bspwm]
type = internal/bspwm

enable-scroll = true
label-focused = %name%
label-focused-background = ${colors.background-wm}
label-focused-underline = ${colors.primary}
label-focused-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 1

format-underline = ${colors.background}
format-background = ${colors.background}
scroll-up = bspwm-desknext
scroll-down = bspwm-deskprev

; Separator in between workspaces
label-separator = |

;==========================================================

[module/xwindow]
;https://github.com/polybar/polybar/wiki/Module:-xwindow
type = internal/xwindow
label = %title:0:30:...%

format-underline = ${colors.background}
format-background = ${colors.background}

;==========================================================

; [module/pacman-packages]
; type = custom/script
; exec = sb-microhpone
; ; click-left = updatepackages
; initial = 1

;==========================================================

[module/pacman-packages]
type = custom/script
exec = sb-updates
; click-left = updatepackages
initial = 1

;==========================================================

[module/volume]
type = custom/ipc
hook-0 = sb-volume
; click-left = $TERMINAL -e pulsemixer &
click-left = $TERMINAL -e pavucontrol &
; click-right = pulsevolctrl "output-mute" "alsa_output.pci-0000_0b_00.4.analog-stereo"
; scroll-up = pulsevolctrl "output-vol" "alsa_output.pci-0000_0b_00.4.analog-stereo" +2%
; scroll-down = pulsevolctrl "output-vol" "alsa_output.pci-0000_0b_00.4.analog-stereo" -2%
initial = 1

;==========================================================

[module/weather]
type = custom/script
exec = curl -s wttr.in/Moscow?format="%t+%h"
interval = 600

;==========================================================

[module/memory]
type = custom/script
exec = sb-memory
label = "%output%"
click-left = $TERMINAL -e htop &
interval = 10

;==========================================================

[module/cpu]
type = custom/script
exec = sb-cpu
label = "%output%"
click-left = $TERMINAL -e htop &
interval = 10

;==========================================================

[module/disk]
type = custom/script
exec = sb-disk
label = "%output%"
interval = 10

;==========================================================

[module/temp]
type = custom/script
exec = sb-temp
label = "%output%"
; click-left = $TERMINAL -e htop &
interval = 10

;==========================================================

[module/wireless-network]
;https://github.com/polybar/polybar/wiki/Module:-network
type = internal/network
interface = wlp3s0

interval = 3

accumulate-stats = true

unknown-as-up = true

format-connected = <ramp-signal> <label-connected>

format-disconnected = <label-disconnected>

; Available tokens:
;   %ifname%    [wireless+wired]
;   %local_ip%  [wireless+wired]
;   %local_ip6% [wireless+wired]
;   %essid%     [wireless]
;   %signal%    [wireless]
;   %upspeed%   [wireless+wired]
;   %downspeed% [wireless+wired]
;   %linkspeed% [wired]
; Default: %ifname% %local_ip%
label-connected = "%essid%"

; Only applies if <ramp-signal> is used
ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 

;==========================================================

[module/eth]
;https://github.com/polybar/polybar/wiki/Module:-network
type = internal/network
interface = enp3s0
interval = 3.0

format-connected = <label-connected>
label-connected = %signal%

;==========================================================

[module/date]
type = custom/script
exec = sb-clock
; click-left = thunderbird &
label = "%output%"
interval = 5

;==========================================================

[module/battery]
type = custom/script
exec = sb-battery
label = "%output%"
; click-left = $TERMINAL -e htop &
interval = 10

;==========================================================

[module/powermenu]
;https://github.com/polybar/polybar/wiki/Module:-menu
type = custom/menu

expand-right = true

format-spacing = 1

label-open = 
label-close =  cancel
label-separator = |
label-separator-foreground = ${colors.foreground-alt}

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = sudo reboot

menu-2-0 = power off
menu-2-0-exec = sudo poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0

;==========================================================
