[colors]
background = ${xrdb:background}
background-wm = ${xrdb:color8}
background-alt = ${xrdb:color0}
foreground = ${xrdb:foreground}
foreground-alt = ${xrdb:color7}
primary = ${xrdb:color4}
alert = ${xrdb:color1}

[settings]
format-foreground =
format-underline = ${colors.primary}
format-background = ${colors.background-alt}
format-padding = 1
format-overline =
format-margin = 0
format-offset = 0
screenchange-reload = true

[global/wm]
;https://github.com/jaagr/polybar/wiki/Configuration#global-wm-settings
margin-top = 0
margin-bottom = 0

[bar/top-bar]
;https://github.com/jaagr/polybar/wiki/Configuration
;monitor = ${env:MONITOR:HDMI-1}

; monitor = ${env:MONITOR:DisplayPort-0}
monitor-fallback =
monitor-strict = false
monitor-exact = true
override-redirect = false
wm-restack = bspwm
enable-ipc = true
fixed-center = false
bottom = false
separator =

width = 100%
height = 24
offset-x = 0
offset-y = 0
radius = 0.0

underline-size = 3
overline-size = 0

background = ${colors.background}
foreground = ${colors.foreground}

module-margin = 2

; font-0 = JetBrainsMonoMedium:pixelsize=10;
font-0 = HackNerdFont:pixelsize=10;
; font-1 = NotoEmoji:fontformat=truetype:scale=10:antialias=false;
font-1 = JoyPixels:fontformat=truetype:scale=8:antialias=false;

modules-left = bspwm xwindow
modules-right = microphone memory cpu disk temp pacman-packages weather brightness volume battery internet date

tray-position = right
tray-padding = 1
tray-background = ${colors.background-alt}
tray-offset-x = 0
tray-offset-y = 0
tray-scale = 1.0

cursor-click = pointer
cursor-scroll = default

[module/bspwm]
type = internal/bspwm

enable-scroll = true
label-focused = %name%
label-focused-background = ${colors.background-wm}
label-focused-underline = ${colors.primary}
label-focused-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 1

format-underline = ${colors.background}
format-background = ${colors.background}
format-padding =
scroll-up = bspwm-desknext
scroll-down = bspwm-deskprev

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%

format-underline = ${colors.background}
format-background = ${colors.background}

[module/microphone]
type = custom/script
exec = sb-microphone
label = "%output%"
; click-left = $TERMINAL -e htop &
interval = 0

[module/memory]
type = custom/script
exec = sb-memory
label = "%output%"
click-left = $TERMINAL -e htop &
interval = 3

[module/cpu]
type = custom/script
exec = sb-cpu
label = "%output%"
click-left = $TERMINAL -e htop &
interval = 3

[module/disk]
type = custom/script
exec = sb-disk
label = "%output%"
interval = 20

[module/temp]
type = custom/script
exec = sb-temp
label = "%output%"
; click-left = $TERMINAL -e htop &
interval = 10

[module/pacman-packages]
type = custom/ipc
hook-0 = sb-updates
initial = 1

[module/weather]
type = custom/script
exec = sb-weather

[module/brightness]
type = custom/ipc
hook-0 = sb-brightness
initial = 1

[module/volume]
type = custom/ipc
hook-0 = sb-volume
; click-left = $TERMINAL -e pulsemixer &
click-left = $TERMINAL -e pavucontrol &
; click-right = pulsevolctrl "output-mute" "alsa_output.pci-0000_0b_00.4.analog-stereo"
; scroll-up = pulsevolctrl "output-vol" "alsa_output.pci-0000_0b_00.4.analog-stereo" +2%
; scroll-down = pulsevolctrl "output-vol" "alsa_output.pci-0000_0b_00.4.analog-stereo" -2%
initial = 1

[module/battery]
type = custom/script
exec = sb-battery
interval = 5

[module/internet]
type = custom/script
exec = sb-internet
interval = 5

[module/date]
type = custom/script
exec = sb-clock
interval = 60

[module/powermenu]
;https://github.com/polybar/polybar/wiki/Module:-menu
type = custom/menu

expand-right = true

format-spacing = 1

label-open = 
label-close =  cancel
label-separator = |
label-separator-foreground = ${colors.foreground-alt}

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = sudo reboot

menu-2-0 = power off
menu-2-0-exec = sudo poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0
